# Версия формата файла docker-compose
version: '3.8'

services:
  backend:
    build: ./backend       # Сборка образа из Dockerfile в папке backend
    ports:
      - "8000:8000"         # Проброс портов: хост:контейнер
    environment:
      - PYTHONUNBUFFERED=1  # Для немедленного вывода логов Python
    volumes:
      - ./backend/app:/app/app  # Монтирование кода для hot-reload
    restart: unless-stopped     # Автоматический перезапуск при падении

  frontend:
    build: ./frontend        # Сборка образа из Dockerfile в папке frontend
    ports:
      - "8501:8501"          # Проброс порта Streamlit
    depends_on:
      - backend              # Ожидание запуска backend сервиса
    environment:
      - PYTHONUNBUFFERED=1   # Для немедленного вывода логов Python
    volumes:
      - ./frontend:/app      # Монтирование кода для hot-reload
    restart: unless-stopped  # Автоматический перезапуск при падении